### ISSUE TITLE
ModuleNotFoundError after installing uxs using pip3

### ISSUE THREAD

**Issue by CedricSchmeits** [binares/uxs#1]
I just installed uxs using the following command: `sudo pip3 install uxs`

The installation was successful so I wanted to try it out.
```
$ ipython3
In [1]: import uxs
...
ModuleNotFoundError: No module named 'tkinter'
```

Of course the sollution is simple `sudo apt install python3-tk`, but I thought I'll let you know.

**Comment by binares** [comment]
@CedricSchmeits Thanks, it is fixed in the latest fons library version, `pip3 install fons --upgrade` (although uxs should be updated as well).

Regarding graphics, your [denario](https://github.com/CedricSchmeits/denario) repo is an idea I have pondered myself (PyQt implemented ccxt trader). Might take a closer look at it at some point (what i have in mind is drawing trendlines on chart for the orders to be auto placed and edited by the current coordinate on the line). 

I also soon plan to add the minimally streamed version for each ccxt exchange (that is fetch methods are polled at an interval).

**Comment by CedricSchmeits** [comment]
I currently have an open standing task within the denario repository where I'm implementing your library. It's just that at this point an other project really needs my attention, so I hope to continue with it during the Christmas holidays.

It's my intention for the denario project that someone can really easy write own strategies that you can then integrate within the views. Also it should possible that picking buy and sell positions on the graph should be done easy. Any suggestions are welcom.
